misitio/blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='index'),
    path('detail/<int:post_id>', views.post_detail, name='detail'),
    path('create', views.post_create, name='create'),
    path('sesion', views.admin, name='admin'),
]

misitio/misitio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('/admin', admin.site.urls),
    path('', include('blog.urls')),
    path('polls/', include('polls.urls'))
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misitio/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

misitio/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
#https://docs.djangoproject.com/es/2.1/howto/initial-data/
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    #file = models.FileField(blank=True, null=True, upload_to="blog")
    file = models.FileField(blank=True, null=True, upload_to="blog")


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def create(self):
        self.save()

misitio/polls/models.py
from django.db import models

# Create your models here.
# https://docs.djangoproject.com/en/2.1/ref/models/fields/#model-field-types


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

misitio/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
# https://docs.djangoproject.com/en/2.1/topics/db/queries/
# https://docs.djangoproject.com/es/2.1/topics/auth/default/


def admin(request):
    if request.method == 'GET':
        if 'logout' in request.GET:
            if request.user.is_authenticated:
                logout(request)
            return HttpResponseRedirect('admin')
        elif 'nouser' in request.GET:
            return render(request,'blog/admin.html', { 'mensaje' : 'Acceso denegado' })
        elif request.user.is_authenticated:
            return HttpResponseRedirect(reverse('blog:index'))

        return render(request, 'blog/admin.html', {})
    elif request.method == 'POST':
        username = request.POST['user']
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            # Para agregar variables en session debe escribir la siguiente línea:
            # request.session['nomre_variable'] = valor_variable
            login(request, user)
            return HttpResponseRedirect(reverse('blog:index'))

    return HttpResponseRedirect('admin?nouser')


def index(request):
    return HttpResponse("Hola mundo")


def post_list(request):
    posts = None
    if request.user.is_authenticated:
        posts = Post.objects.all().order_by('published_date')
    else:
        posts = Post.objects.filter(
            published_date__lte=timezone.now()).order_by('published_date')
    error = None
    if 'error' in request.session:
        error = request.session['error']
        del request.session['error']
        
    return render(request, 'blog/post_list.html', {'posts': posts, 'error': error})


def post_create(request):
    if not request.user.is_authenticated or request.user.has_perm('blog_add') == False:
        request.session['error'] = "Sin autorización para agregar nuevos post"
        return HttpResponseRedirect(reverse('blog:index'))

    if request.method == 'GET':
        return render(request, 'blog/post_create.html', {})
    elif request.method == 'POST':
        message = ""

        try:
            post = Post()
            post.author = request.user
            post.title = request.POST.get('title')
            post.text = request.POST.get('text')
            published_date = request.POST.get('published_date')
            
            #post.published_date = lambda published_date : None if published_date == "" else request.POST.get('published_date')
            post.save()
            file = request.FILES['file']
            ext = file.name.split(".")[-1]
            file.name = str(post.pk) + "." + ext
            post.file = file
            post.save()
            message = "Éxito al guardar la publicación"
            return HttpResponseRedirect(reverse('blog:detail', args=(post.pk,)))
        except Exception as e:
            message = "Error al guardar la publicación: " + str(e)
            return render(request, 'blog/post_create.html', {'message': message})
    else:
        response = HttpResponse('Método no permitido')
        response.status_code = 405
        return response


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        post.publish()

    try:
        return render(request, 'blog/post_detail.html', {'post': post})
    except Exception as e:
        response = HttpResponse("Error al guardar la publicación: " + str(e))
        response.status_code = 404
        return response

misitio/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """ Return the last five published question.  """
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message' : "You didn't select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

misitio/blog/templates/blog/admin.html
<form method="POST">
    {% csrf_token %}
    <label>user</label>
    <input type="text" name="user">
    <br>
    <label>password</label>
    <input type="password" name="password">
    <br>
    <input type="submit" value="Autenticar">
</form>

{{ mensaje }}

misitio/blog/templates/blog/post_create.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'blog:index' %}">Volver a la lista</a>
<div>
    {{ message }}
</div>
<br>
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <label>
        Autor
    </label>
    {{ request.user.username }}
    <br />
    <label>
        Titulo
    </label>
    <input type="text" name="title">
    <br />

    <label>
        Texto
    </label>
    <textarea name="text"></textarea>
    <br />
    <label>
        Fecha de publicación
    </label>
    <input type="datetime" name="published_date">
    <br>
    <label>Archivo</label>
    <input type="file" name="file">
    <br>
    <input type="submit" value="Crear post">

</form>


{% endblock content %}

misitio/blog/templates/blog/post_detail.html
{% extends "base.html" %}



{% block content %}

<a href="{% url 'blog:index' %}">Volver a la lista</a>
{% if post.published_date == None %}
    <form method="POST" action="{% url 'blog:detail' post.pk %}">
        {% csrf_token %}
        <input type="hidden" value="{{post.pk}}">
        <input type="submit" value="Publicar">
    </form>
{% endif %}
<div>
    <p>published: {{ post.published_date }}</p>
    <h1><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></h1>
    <p>{{ post.text|linebreaksbr }}</p>
</div>


{% endblock content %}

misitio/blog/templates/blog/post_list.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/blog.css' %}">

<h1>POSTS</h1>
{% if request.user.is_authenticated %}
<ul>

    <li>
        <a href="{% url 'blog:admin'%}?logout">Cerrar Sesión</a>
    </li>
    <li>
        <a href="{% url 'blog:create'  %}">Crear post</a>
    </li>
    {% if error %}
    <li>
        {{ error }}
    </li>
    {% endif %}
</ul>
{% else %}
<br>
<a href="{% url 'blog:admin' %}">Iniciar Sesión</a>
<br>
{% endif %}

{{ posts }}



{% for post in posts %}
<div>
    <p>published: {{ post.published_date }}</p>
    <h1><a href="{% url 'blog:detail' post.pk%}">
            {% if post.title %}
                {{ post.title }}
            {% else %}
                {{ post.pk }}
            {% endif %}
        </a></h1>
    <p>{{ post.text|linebreaksbr }}</p>
</div>
{% endfor %}

misitio/polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ question.question_text }} </h1>
{% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}

{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }} </label>
    <br>
{% endfor %}
<input type="submit" value="Vote">
</form>
{% endblock content %}

misitio/polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock content %}

misitio/polls/templates/polls/results.html
<h1> {{ question.question_text }} </h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

misitio/templates/base.html
<!doctype html>
<html>
    <head>
        <style>
            h1 {
                color:red
            }
        </style>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>